# Generated by Django 3.1 on 2020-02-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('idApi', models.IntegerField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('speed', models.FloatField()),
                ('specialDefense', models.FloatField()),
                ('specialAttack', models.FloatField()),
                ('defense', models.FloatField()),
                ('attack', models.FloatField()),
                ('hp', models.FloatField()),
                ('prevolution', models.CharField(max_length=100, null=True)),
                ('evolution', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
